### ISSUE TITLE
Rust syntax

### ISSUE THREAD

**Issue by Tau5** [klange/bim#11]
Add syntax highlighting for Rust

**Comment by klange** [comment]
![screenshot from 2018-11-01 09-17-11](https://user-images.githubusercontent.com/223546/47825751-fcced580-ddb6-11e8-9fa9-ae9d58a5852a.png)

**Comment by klange** [comment]
I can't properly support Rust's nested `/* c-style comments */` with this syntax highlighting approach, though.
