### ISSUE TITLE
Assembly syntax and relative numbers justify

### ISSUE THREAD

**Issue by 8dcc** [klange/bim#32]
Hello, first of all I wanted to thank you for making such an amazing and lightweight editor.

I would like to suggest 2 things:
* Assembly syntax for `.asm` and `.s` files. I would like to see intel syntax and I also think it would be easier to implement, but obviously that's up to you.
* Justify the current line number to the left when `relativenumbers=1`. For example in vim it's displayed like this, and I think it is more readable (of course you could just add an option to toggle justify):
  ![image](https://user-images.githubusercontent.com/29655971/218311701-3eee3664-29f2-4743-885a-6377276eafb0.png)

**Comment by klange** [comment]
Please try to post separate issues for different feature requests so that they can be addressed individually.

There is a highlighter for GNU/AT&T syntax x86 assembly, since that is what ToaruOS uses: https://github.com/klange/bim/blob/master/syntax/gas.krk

Here is a quick patch to left-align the current line for `relativenumbers` mode:

```diff
diff --git a/bim.c b/bim.c
index 85819c1..96cba7a 100644
--- a/bim.c
+++ b/bim.c
@@ -2574,6 +2574,12 @@ int gutter_width(void) {
 	return env->gutter;
 }
 
+static void pad_numbers(int x, int num_size) {
+	for (int y = 0; y < num_size - log_base_10(x + 1); ++y) {
+		printf(" ");
+	}
+}
+
 /**
  * Draw the gutter and line numbers.
  */
@@ -2590,10 +2596,9 @@ void draw_line_number(int x) {
 		x = ((x < 0) ? -x : x)-1;
 	}
 	int num_size = num_width() - 2; /* Padding */
-	for (int y = 0; y < num_size - log_base_10(x + 1); ++y) {
-		printf(" ");
-	}
+	if (!global_config.relative_lines || x+1 != env->line_no) pad_numbers(x, num_size);
 	printf("%d%c", x + 1, ((x+1 == env->line_no || global_config.horizontal_shift_scrolling) && env->coffset > 0) ? '<' : ' ');
+	if (global_config.relative_lines && x+1 == env->line_no) pad_numbers(x,num_size);
 }
 
 /**
```

**Comment by 8dcc** [comment]
Didn't know there was AT&T assembly highlighting.

The patch is what I was looking for, thank you.
